# Generated by Django 3.2.8 on 2021-10-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testdata',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('doi', models.TextField(blank=True, null=True)),
                ('incitations', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testdata',
                'managed': False,
            },
        ),
    ]
